metricbeat.modules:
  - module: system
    period: 1m
    metricsets:
      - cpu
      - memory
      - filesystem
      - fsstat
      - uptime
    cpu.metrics: ["percentages", "normalized_percentages"]
    core.metrics: ["percentages"]
    hostfs: /hostfs

  - module: docker
    period: 1m
    hosts: ["unix:///var/run/docker.sock"]
    metricsets:
      - container
      - cpu
      - healthcheck
      - memory

processors:
  - add_host_metadata: ~
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.template.enabled: true
setup.template.name: "metricbeat"
setup.template.pattern: "metricbeat*"
setup.template.overwrite: true

http.enabled: true
http.host: 0.0.0.0
http.port: 5066
