input {
  gelf {
    port => 12201
  }

  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [tag] and ![service] {
    mutate {
      add_field => { "service" => "%{tag}" }
    }
  }

  if [container_name] and ![service] {
    mutate {
      add_field => { "service" => "%{container_name}" }
    }
  }

  if ![service] {
    mutate {
      add_field => { "service" => "unknown-service" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "studyvault-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
