metricbeat.modules:
  - module: system
    period: 10s
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - filesystem
      - fsstat
      - uptime
    processes: [".*"]
    cpu.metrics: ["percentages", "normalized_percentages"]
    core.metrics: ["percentages"]
    hostfs: /hostfs

  - module: docker
    period: 10s
    hosts: ["unix:///var/run/docker.sock"]
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network

processors:
  - add_host_metadata: ~
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "metricbeat-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.ilm.enabled: false
setup.template.enabled: true
setup.template.name: "metricbeat"
setup.template.pattern: "metricbeat-*"
setup.template.overwrite: true

http.enabled: true
http.host: 0.0.0.0
http.port: 5066
