#!/bin/sh
set -eu

envsubst '${STUDYVAULT_AUTH_RATE} ${STUDYVAULT_AUTH_NAV_RATE} ${STUDYVAULT_UPLOAD_RATE} ${STUDYVAULT_SEARCH_RATE} ${STUDYVAULT_ADMIN_RATE} ${STUDYVAULT_AUTH_BURST} ${STUDYVAULT_AUTH_NAV_BURST} ${STUDYVAULT_UPLOAD_BURST} ${STUDYVAULT_SEARCH_BURST} ${STUDYVAULT_ADMIN_BURST}' \
  < /etc/nginx/templates/nginx.conf.template \
  > /etc/nginx/nginx.conf

exec nginx -g 'daemon off;'
